### ISSUE TITLE
오타가 있습니다

### ISSUE THREAD

**Issue by BEMELON** [kosslab-kr/GSharp.Modules#3]
GSharp.Moudles.ConnectWeb	
GSharp.Moudles.Cpu	
GSharp.Moudles.Ram	
GSharp.Moudles.RegDelete	
Gsharp.Moudles.Ipv4

Moudles 라 되어있네요.

**Comment by BEMELON** [comment]
제가 풀리퀘 보낼때 같이 수정해서 보내겠습니다

**Comment by BEMELON** [comment]
폴더명은 어떻게 수정해야 될지 모르겠네요. 수정 못했습니다 ㅠㅠㅠ

**Comment by ghost** [comment]
앗! 오타가 있었군요. 감사합니다.

**Comment by iodes** [comment]
ac846001f5f2c0d88f54478315553f27459ab5ae
정리하면서 오타 함께 수정하였습니다.
